name: Build PR
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, unlabeled]
jobs:
  linux-x86_64:
    if: github.event_name != 'unlabeled' || github.event.label.name == 'CI Build'
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.1-cudnn7-devel-centos7
    steps:
      - name: Install environment
        run: |
          yum -y update
          yum -y install centos-release-scl-rh epel-release
          yum -y install java-1.8.0-openjdk-devel
          echo Downloading Maven
          curl -L https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -o $HOME/apache-maven-3.6.3-bin.tar.gz
          tar xzf $HOME/apache-maven-3.6.3-bin.tar.gz -C /opt/
          ln -sf /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        run: |
          git --version
          mvn -version
          df -h
          echo "Fixing HOME to /root (was '$HOME')"
          export HOME=/root
          mkdir -p $HOME/.m2
          mvn clean install -Possrh,dev -B -U -e -Djavacpp.platform=linux-x86_64
          df -h
  macosx-x86_64:
    if: github.event_name != 'unlabeled' || github.event.label.name == 'CI Build'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        run: |
          git --version
          mvn -version
          mkdir -p $HOME/.m2
          df -h
          mvn clean install -Possrh,dev -B -U -e -Djavacpp.platform=macosx-x86_64 -Djavacpp.platform.extension=${{ matrix.ext }}
          df -h
  windows-x86_64:
    if: github.event_name != 'unlabeled' || github.event.label.name == 'CI Build'
    runs-on: windows-latest
    steps:
      - name: Configure page file
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        shell: cmd
        run: |
          git --version
          call mvn -version
          mkdir %USERPROFILE%\.m2
          df -h
          wmic pagefile list /format:list
          call mvn clean install -Possrh,dev -B -U -e -Djavacpp.platform=windows-x86_64 -Djavacpp.platform.extension=${{ matrix.ext }}
          if ERRORLEVEL 1 exit /b
          df -h
          wmic pagefile list /format:list
